# Generated by Django 5.0.7 on 2024-07-23 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, max_length=200, unique=True
            ),
            preserve_default=False,
        ),
    ]
